version: '3.8'

services:
  funasr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: funasr-server
    ports:
      - "28717:28717"
    restart: unless-stopped
    networks:
      - 1panel-network
    # 挂载模型缓存（ModelScope 默认缓存目录）
    volumes:
      - ./models:/root/.cache/modelscope
    environment:
      - PYTHONUNBUFFERED=1

networks:
  1panel-network:
    external: true
